"""Pick an anomaly-decision threshold for a per-ID model and export it to firmware.

AUC (Phase 0/1) measures ranking without committing to a cutoff; to actually
*decide* normal vs anomalous on-device we need a threshold. We set it from the
NORMAL training clips only (unsupervised -- no anomaly labels used to choose it):
threshold = the given percentile of normal-training per-clip reconstruction MSE.
A higher percentile = fewer false alarms but more missed anomalies.

We then report precision/recall/F1/accuracy at that threshold on the held-out
test set so its quality is visible, and write:
    ml/artifacts/per_id/<id>/threshold.json
    firmware/main/threshold.h   (constexpr float kAnomalyThreshold + provenance)

Uses the float32 Keras model for speed; on-device int8 scores match it to ~0.001
(verified in Phase 1), so the threshold transfers directly.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import config
import data
import numpy as np
import tensorflow as tf
from train import normalize
from train_per_id import group_by_id


def clip_scores(model, files, mean, std):
    scores = []
    for _, path, *rest in files:
        vectors = data.cached_file_to_vectors(path)
        if len(vectors) == 0:
            scores.append(0.0)
            continue
        vectors = normalize(vectors, mean, std)
        recon = model.predict(vectors, verbose=0)
        scores.append(float(np.mean((vectors - recon) ** 2)))
    return np.array(scores)


def metrics_at(threshold, scores, labels):
    pred = (scores > threshold).astype(int)
    tp = int(((pred == 1) & (labels == 1)).sum())
    fp = int(((pred == 1) & (labels == 0)).sum())
    fn = int(((pred == 0) & (labels == 1)).sum())
    tn = int(((pred == 0) & (labels == 0)).sum())
    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    accuracy = (tp + tn) / len(labels) if len(labels) else 0.0
    return {"tp": tp, "fp": fp, "fn": fn, "tn": tn,
            "precision": round(precision, 4), "recall": round(recall, 4),
            "f1": round(f1, 4), "accuracy": round(accuracy, 4)}


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--machine-id", default="id_02")
    p.add_argument("--percentile", type=float, default=90.0,
                   help="Percentile of normal-training scores used as the threshold")
    return p.parse_args()


def main():
    args = parse_args()
    id_dir = config.PER_ID_ARTIFACTS / args.machine_id
    model = tf.keras.models.load_model(id_dir / "model.keras")
    stats = np.load(id_dir / "normalization.npz")
    mean, std = stats["mean"], stats["std"]

    train_files, test_files = data.build_dataset()
    train_norm = [f for f in group_by_id(train_files).get(args.machine_id, [])]
    test_id = group_by_id(test_files).get(args.machine_id, [])

    print(f"[data] {args.machine_id}: {len(train_norm)} normal-train clips, "
          f"{len(test_id)} test clips -- scoring (a minute or two)...")
    train_scores = clip_scores(model, train_norm, mean, std)
    threshold = float(np.percentile(train_scores, args.percentile))
    print(f"[threshold] {args.percentile:.0f}th pct of normal-train scores = "
          f"{threshold:.6f}")

    test_scores = clip_scores(model, test_id, mean, std)
    test_labels = np.array([lbl for _, _, lbl in test_id])
    m = metrics_at(threshold, test_scores, test_labels)
    print(f"[test @ threshold] precision={m['precision']} recall={m['recall']} "
          f"F1={m['f1']} accuracy={m['accuracy']}  "
          f"(TP={m['tp']} FP={m['fp']} FN={m['fn']} TN={m['tn']})")

    result = {"machine_id": args.machine_id, "percentile": args.percentile,
              "threshold": round(threshold, 6),
              "normal_train_clips": len(train_norm), "test": m}
    (id_dir / "threshold.json").write_text(json.dumps(result, indent=2))

    header = Path(__file__).resolve().parents[1] / "firmware" / "main" / "threshold.h"
    header.write_text(
        "// Auto-generated by ml/compute_threshold.py -- do not edit by hand.\n"
        "// Anomaly-decision threshold on the per-clip mean reconstruction MSE.\n"
        f"// machine={args.machine_id}  percentile={args.percentile:.0f}  "
        f"test F1={m['f1']} recall={m['recall']}\n"
        "#pragma once\n"
        f"constexpr float kAnomalyThreshold = {threshold:.6f}f;\n"
    )
    print(f"[saved] {id_dir / 'threshold.json'}")
    print(f"[saved] {header}")


if __name__ == "__main__":
    main()
