"""Quantize the trained autoencoder to full int8 and emit a C header for TFLite-Micro.

Reads ml/artifacts/model.keras + rep_vectors.npy (written by train.py) and produces:
    ml/artifacts/model_int8.tflite   -- the deployable model
    ml/artifacts/model_data.cc       -- C byte array, copy to firmware/main/ in Phase 1

Full-integer quantization (int8 in / int8 out) is what TFLite-Micro needs on the ESP32.
"""
from __future__ import annotations

from pathlib import Path

import config
import numpy as np
import tensorflow as tf


def _representative_dataset(vectors: np.ndarray):
    def gen():
        for v in vectors:
            yield [v.reshape(1, -1).astype(np.float32)]
    return gen


def to_int8_tflite(model: tf.keras.Model, rep_vectors: np.ndarray) -> bytes:
    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = _representative_dataset(rep_vectors)
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    return conv.convert()


def tflite_to_c_header(tflite_bytes: bytes, var_name: str, out_path: Path) -> None:
    lines = [
        "// Auto-generated by ml/export_tflite.py -- do not edit by hand.",
        '#include "model_data.h"',
        "",
        f"alignas(16) const unsigned char {var_name}[] = {{",
    ]
    for i in range(0, len(tflite_bytes), 12):
        chunk = tflite_bytes[i:i + 12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const unsigned int {var_name}_len = {len(tflite_bytes)};")
    out_path.write_text("\n".join(lines) + "\n")

    header = out_path.with_suffix(".h")
    header.write_text(
        "// Auto-generated by ml/export_tflite.py -- do not edit by hand.\n"
        "#pragma once\n"
        f"extern const unsigned char {var_name}[];\n"
        f"extern const unsigned int {var_name}_len;\n"
    )


def main() -> None:
    if not config.MODEL_KERAS.exists():
        raise FileNotFoundError("Run train.py first (no model.keras in artifacts/).")

    model = tf.keras.models.load_model(config.MODEL_KERAS)
    rep = np.load(config.REP_VECTORS)
    tflite_bytes = to_int8_tflite(model, rep)

    config.TFLITE_INT8.write_bytes(tflite_bytes)
    tflite_to_c_header(tflite_bytes, config.C_VAR_NAME, config.C_HEADER)

    print(f"[saved] {config.TFLITE_INT8}  ({len(tflite_bytes) / 1024:.1f} KiB)")
    print(f"[saved] {config.C_HEADER}")
    print("[next] copy model_data.cc / model_data.h into firmware/main/ for Phase 1")


if __name__ == "__main__":
    main()
